config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        #,
        #omniauth_callbacks: 'users/omniauth_callbacks',
        sessions: 'users/sessions'
      }
  root 'items#index'
  resources :items do
    member do
      get :confirm
      post :purchase
    end
  end

  as :user do

    get "/sign_up/registration" => "users/registrations#registration"#会員情報入力
    post "/sign_up/tel" => 'users/registrations#tel'#電話番号登録
    post "/sign_up/address" => 'users/registrations#address'#住所確認
    post "/sign_up/credit" => 'users/registrations#credit'#クレジットカード
    post "/sign_up/create" => 'users/registrations#create'#DBに保存
    get "/sign_up/done" => 'users/registrations#done'#完了ページ
    get "/users/:id/profile" => 'users#profile', as: :user_profile
    patch "/users/:id/profile" => 'users#profile_update' , as: :update_user_profile
    get "/users/:id/logout" => "users#logout", as: :user_logout
  end

  resources :cards, only: [:index, :new, :destroy, :create]

  #get "users/sign_up/registration", to: "users#new"
  resources :phonenumber
  resources :address
  resources :creditcards
  resources :users, only: [:index, :edit, :new] do
    member do
      get :logout
      get :register
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one  :phonenumber,dependent: :destroy
  has_one :address,dependent: :destroy
  has_one :profile
  has_many :cards
  has_many :items
  # has_many :comments

  accepts_nested_attributes_for :address

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end
  def facebook
    callback_for(:facebook)
  end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end
  def google_oauth2
    callback_for(:google)
  end

  # protected
  def callback_for(provider)
    @user = User.find_or_create_from_auth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #after_sign_in_path_forと同じパス
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_path
    end
  end

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   #before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
   #prepend_before_action :check_captcha, only: [:create]
  # GET /resource/sign_up


  def registration
    # unless session[:user] == nil
    #   @user = User.new(session[:user])
    #   nickname = @user.nickname
    #   email = @user.email
    # end
    @user = User.new(session[:user])
    nickname = @user.nickname
    email = @user.email

  end

  def tel
    session[:nickname] = params[:session][:nickname]
    session[:email] = params[:session][:email]
    session[:password] = params[:session][:password]
    session[:password_confirmation] = params[:session][:password_confirmation]
    session[:family_name] = params[:session][:family_name]
    session[:first_name] = params[:session][:first_name]
    session[:family_name_kana] = params[:session][:family_name_kana]
    session[:first_name_kana] = params[:session][:first_name_kana]
    # 誕生日
    birth_year = params[:session][:"birthday_data(1i)"].to_i
    birth_month = params[:session][:"birthday_data(2i)"].to_i
    birth_day = params[:session][:"birthday_data(3i)"].to_i
    unless birth_year == 0 || birth_month == 0 || birth_day == 0
      session[:birthday_data] = Date.new(birth_year, birth_month , birth_day)
    end

  end

  def address
    session[:phone_number] = params[:session][:phone_number]
  end

  def credit
  end


  def done
  end

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    session[:postal_code] = params[:session][:postal_code]
    session[:prefecture] = params[:session][:prefecture]
    session[:city] = params[:session][:city]
    session[:street_address] = params[:session][:street_address]
    session[:building] = params[:session][:building]

    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      family_name: session[:family_name],
      first_name: session[:first_name],
      family_name_kana: session[:family_name_kana],
      first_name_kana: session[:first_name_kana],
      birthday_data: session[:birthday_data],
      phone_number: session[:phone_number]
      )

    @user.address = @user.build_address(
      postal_code: session[:postal_code],
      prefecture: session[:prefecture],
      city: session[:city],
      street_address: session[:street_address],
      building: session[:building]
      )

    @user.save


    #deviseで新規登録を行うと自動でアカウントが切り替わる問題解決
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(@user, current_user)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      render action: :registration
      clean_up_passwords resource
      set_minimum_password_length
    end

  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.



 private

  def after_sign_up_path_for(resource)
    sign_up_done_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    sign_up_done_path
  end


  def check_captcha
    self.resource = resource_class.new sign_up_params
    resource.validate
    respond_with_navigational(resource) { render :new } unless verify_recaptcha(model: resource)
  end



  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  prepend_before_action :check_captcha, only: [:create]


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  private

  def check_captcha
    self.resource = resource_class.new sign_in_params
    resource.validate
    respond_with_navigational(resource) { render :new } unless verify_recaptcha(model: resource)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  before_action :set_parents
  before_action :set_user, except: [:new]

  def index
  end

  def edit
  end

  def register
  end

  def logout
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def set_parents
    @parents = Category.limit(14)
  end

  def set_user
    @user = User.find(current_user.id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_leftbar-edit-mypage.html.haml
.leftbar
  .mypage-nav
    %ul.mypage-nav__list

      %li
        = link_to users_path, class: 'mypage-nav__list--item' do
          マイページ


      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          お知らせ
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          やることリスト
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          いいね一覧！
          %i.fas.fa-chevron-right

      %li
        = link_to new_item_path, class: 'mypage-nav__list--item' do
          出品する
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-出品中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-取引中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-売却済み
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          購入した商品-取引中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          購入した商品-過去の取引
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ニュース一覧
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          評価一覧
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ガイド
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          お問い合わせ
          %i.fas.fa-chevron-right

  .merupay-nav-head
    %h3 メルペイ

    %ul.mypage-nav-list
      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          売上・振込申請
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ポイント
          %i.fas.fa-chevron-right

    .setting-nav-head
      %h3 設定
      = link_to edit_user_path(current_user.id), class: 'mypage-nav__list--item__profile' do
        プロフィール

        %i.fas.fa-chevron-right
      %ul.mypage-nav-list
        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            発送元・お届け先住所変更
            %i.fas.fa-chevron-right

        %li
          = link_to cards_path, class: 'mypage-nav__list--item' do
            支払い方法
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            メール・パスワード
            %i.fas.fa-chevron-right

        %li
          = link_to register_user_path(current_user.id), class: 'mypage-nav__list--item' do
            本人情報
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            電話番号の確認
            %i.fas.fa-chevron-right

        %li
          = link_to logout_user_path(current_user.id), class: 'mypage-nav__list--item' do
            ログアウト
            %i.fas.fa-chevron-right

app/views/users/_leftbar-logout.html.haml
.leftbar
  .mypage-nav
    %ul.mypage-nav__list

      %li
        = link_to users_path, class: 'mypage-nav__list--item' do
          マイページ
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          お知らせ
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          やることリスト
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          いいね一覧！
          %i.fas.fa-chevron-right

      %li
        = link_to new_item_path, class: 'mypage-nav__list--item' do
          出品する
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-出品中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-取引中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-売却済み
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          購入した商品-取引中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          購入した商品-過去の取引
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ニュース一覧
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          評価一覧
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ガイド
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          お問い合わせ
          %i.fas.fa-chevron-right

  .merupay-nav-head
    %h3 メルペイ

    %ul.mypage-nav-list
      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          売上・振込申請
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ポイント
          %i.fas.fa-chevron-right

    .setting-nav-head
      %h3 設定
      %ul.mypage-nav-list

        %li
          = link_to edit_user_path(current_user.id), class: 'mypage-nav__list--item' do
            プロフィール
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            発送元・お届け先住所変更
            %i.fas.fa-chevron-right
            
        %li
          = link_to cards_path, class: 'mypage-nav__list--item' do
            支払い方法
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            メール・パスワード
            %i.fas.fa-chevron-right

        %li
          = link_to register_user_path(current_user.id), class: 'mypage-nav__list--item' do
            本人情報
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            電話番号の確認
            %i.fas.fa-chevron-right

      = link_to logout_user_path(current_user.id), class: 'mypage-nav__list--item__logout' do
        ログアウト
        %i.fas.fa-chevron-right

app/views/users/_leftbar-mypage.html.haml
.leftbar
  .mypage-nav
    = link_to users_path, class: 'mypage-nav__list--item__mypage' do
      マイページ
      %i.fas.fa-chevron-right

    %ul.mypage-nav__list
      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          お知らせ
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          やることリスト
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          いいね一覧！
          %i.fas.fa-chevron-right

      %li
        = link_to new_item_path, class: 'mypage-nav__list--item' do
          出品する
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-出品中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-取引中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-売却済み
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          購入した商品-取引中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          購入した商品-過去の取引
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ニュース一覧
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          評価一覧
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ガイド
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          お問い合わせ
          %i.fas.fa-chevron-right

  .merupay-nav-head
    %h3 メルペイ
    %ul.mypage-nav-list
      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          売上・振込申請
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ポイント
          %i.fas.fa-chevron-right

    .setting-nav-head
      %h3 設定
      %ul.mypage-nav-list
        %li
          = link_to edit_user_path(current_user.id), class: 'mypage-nav__list--item' do
            プロフィール
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            発送元・お届け先住所変更
            %i.fas.fa-chevron-right

        %li
          = link_to cards_path, class: 'mypage-nav__list--item' do
            支払い方法
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            メール・パスワード
            %i.fas.fa-chevron-right

        %li
          = link_to register_user_path(current_user.id), class: 'mypage-nav__list--item' do
            本人情報
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            電話番号の確認
            %i.fas.fa-chevron-right

        %li
          = link_to logout_user_path(current_user.id), class: 'mypage-nav__list--item' do
            ログアウト
            %i.fas.fa-chevron-right

app/views/users/_leftbar-register.html.haml
.leftbar
  .mypage-nav
    %ul.mypage-nav__list

      %li
        = link_to users_path, class: 'mypage-nav__list--item' do
          マイページ
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          お知らせ
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          やることリスト
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          いいね一覧！
          %i.fas.fa-chevron-right

      %li
        = link_to new_item_path, class: 'mypage-nav__list--item' do
          出品する
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-出品中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-取引中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-売却済み
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          購入した商品-取引中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          購入した商品-過去の取引
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ニュース一覧
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          評価一覧
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ガイド
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          お問い合わせ
          %i.fas.fa-chevron-right

  .merupay-nav-head
    %h3 メルペイ

    %ul.mypage-nav-list
      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          売上・振込申請
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ポイント
          %i.fas.fa-chevron-right

    .setting-nav-head
      %h3 設定
      %ul.mypage-nav-list

        %li
          = link_to edit_user_path(current_user.id), class: 'mypage-nav__list--item' do
            プロフィール
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            発送元・お届け先住所変更
            %i.fas.fa-chevron-right

        %li
          = link_to cards_path, class: 'mypage-nav__list--item' do
            支払い方法
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            メール・パスワード
            %i.fas.fa-chevron-right

        = link_to register_user_path(current_user.id), class: 'mypage-nav__list--item__register' do
          本人情報
          %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            電話番号の確認
            %i.fas.fa-chevron-right

        %li
          = link_to logout_user_path(current_user.id), class: 'mypage-nav__list--item' do
            ログアウト
            %i.fas.fa-chevron-right

app/views/users/_leftbar.html.haml
.leftbar
  .mypage-nav
    %ul.mypage-nav__list

      %li
        = link_to users_path, class: 'mypage-nav__list--item' do
          マイページ
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          お知らせ
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          やることリスト
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          いいね一覧！
          %i.fas.fa-chevron-right

      %li
        = link_to new_item_path, class: 'mypage-nav__list--item' do
          出品する
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-出品中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-取引中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          出品した商品-売却済み
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          購入した商品-取引中
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          購入した商品-過去の取引
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ニュース一覧
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          評価一覧
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ガイド
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          お問い合わせ
          %i.fas.fa-chevron-right

  .merupay-nav-head
    %h3 メルペイ

    %ul.mypage-nav-list
      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          売上・振込申請
          %i.fas.fa-chevron-right

      %li
        = link_to '#', class: 'mypage-nav__list--item' do
          ポイント
          %i.fas.fa-chevron-right

    .setting-nav-head
      %h3 設定
      %ul.mypage-nav-list

        %li
          = link_to edit_user_path(current_user.id), class: 'mypage-nav__list--item' do
            プロフィール
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            発送元・お届け先住所変更
            %i.fas.fa-chevron-right

        %li
          = link_to cards_path, class: 'mypage-nav__list--item' do
            支払い方法
            %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            メール・パスワード
            %i.fas.fa-chevron-right

        = link_to register_user_path(current_user.id), class: 'mypage-nav__list--item' do
          本人情報
          %i.fas.fa-chevron-right

        %li
          = link_to '#', class: 'mypage-nav__list--item' do
            電話番号の確認
            %i.fas.fa-chevron-right

        %li
          = link_to logout_user_path(current_user.id), class: 'mypage-nav__list--item' do
            ログアウト
            %i.fas.fa-chevron-right

app/views/users/new.html.haml
.wrapper
  .sign-up-header
    =link_to image_tag("mercari_logo_color.svg"), "root_path", class: "sign-up-logo"
  .single-main
    .single-main-container
      %h2.single-main-container__head 新規会員登録
      .single-main-container__inner
        .single-main-container__inner--content
          =link_to sign_up_registration_path, method: :get, class: 'btn-default btn-mail' do
            %span メールアドレスで登録
            %i.far.fa-envelope

          = link_to '#' ,class: 'btn-default btn-sns-facebook' do
            %strong Facebookで登録

          = link_to '#', class: "btn-default btn-sns-google" do
            = image_tag(("google icon.jpg"), class: "goole-icon")
            %em Googleで登録

=render 'shared/sign-up-footer'