config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        #,
        #omniauth_callbacks: 'users/omniauth_callbacks',
        sessions: 'users/sessions'
      }
  root 'items#index'
  resources :items do
    member do
      get :confirm
      post :purchase
    end
  end

  as :user do

    get "/sign_up/registration" => "users/registrations#registration"#会員情報入力
    post "/sign_up/tel" => 'users/registrations#tel'#電話番号登録
    post "/sign_up/address" => 'users/registrations#address'#住所確認
    post "/sign_up/credit" => 'users/registrations#credit'#クレジットカード
    post "/sign_up/create" => 'users/registrations#create'#DBに保存
    get "/sign_up/done" => 'users/registrations#done'#完了ページ
    get "/users/:id/profile" => 'users#profile', as: :user_profile
    patch "/users/:id/profile" => 'users#profile_update' , as: :update_user_profile
    get "/users/:id/logout" => "users#logout", as: :user_logout
  end

  resources :cards, only: [:index, :new, :destroy, :create]

  #get "users/sign_up/registration", to: "users#new"
  resources :phonenumber
  resources :address
  resources :creditcards
  resources :users, only: [:index, :edit, :new] do
    member do
      get :logout
      get :register
    end
  end
end

app/views/shared/_card-method-breadcrumbs.html.haml
%nav.common-breadcrumbs
  - breadcrumb :cards
  = breadcrumbs separator: " &#8811; "
  

app/views/shared/_category-children.html.haml
%li.category-children
  - parents.each do |parent|
    - parent.children.each do |child|
      %h6 #{child.name}

app/views/shared/_category-grandchildren.html.haml
- parents.each do |parent|
  - parent.children.each do |child|
    - child.children.each do |grandchild|
      =grandchild.name

app/views/shared/_category-parents.html.haml
- parents.each do |parent|
  %li.pc-header-nav-parent
    %h5 #{parent.name}

    %ul.pc-header-nav-children-wrap
      - if parent.children.present?
        - parent.children.each do |child|
          %li.category-children
            %h6 #{child.name}

            %ul.pc-header-nav-grandchild-wrap
              - if child.children.present?
                - child.children.each do |grandchild|
                  %li.category-children
                    %h6 #{grandchild.name}
                    

app/views/shared/_footer.html.haml
.footer
  .footer__top
    .footer__top__cell
      %h2 メルカリについて
      %ul
        %li 会社概要（運営会社）
        %li 採用情報
        %li プレスリリース
        %li 公式ブログ
        %li メルカリロゴ利用ガイドライン
        %li.sns-btn
          =link_to 'https://twitter.com/mercari_jp' do
            %i.fab.fa-twitter.fa-lg
          =link_to 'https://www.facebook.com/mercarijp' do
            %i.fab.fa-facebook
    .footer__top__cell
      %h2 ヘルプ&ガイド
      %ul
        %li メルカリガイド
        %li らくらくメルカリ便
        %li ゆうゆうメルカリ便
        %li 大型メルカリ便
        %li 車体取引ガイド
        %li メルカリあんしん・あんぜん宣言！
        %li 偽ブランド品撲滅への取り組み
        %li メルカリボックス
    .footer__top__cell
      %h2 プライバシーと利用規約
      .footer__top__cell__dual-box
        .footer__top__cell__dual-box--inner-left
          %ul
            %li プライバシーボリシー
            %li メルカリ利用規約
            %li あんしんスマホサポート制度に関する利用特約
            %li コンプライアンスポリシー
        .footer__top__cell__dual-box--inner-right
          %ul
            %li 個人データの安全管理に関わる基本方針
            %li 特定商取引に関する表記
            %li 資金決済法に基づく表示
            %li 法令遵守と犯罪抑止のために
            %li 返品・返金ポリシー
    .footer__top__cell
      %h2 国
      %ul
        %li 日本
        %li United States
  .footer__bottom
    = link_to root_path do
      = image_tag "mercari_logo_white.svg"
    .footer__bottom--copyright
      %small © 2019 Mercari

app/views/shared/_header.html.haml
%header.pc-header.visible-pc
  .pc-header__box
    .pc-header__box__top
      %h1.pc-header__box__top--logo
        = link_to root_path do
          = image_tag "mercari_logo_color.svg", alt: 'mercari'
      = form_with url: '#', class: "pc-header__box__top--search-box" do |form|
        = form.text_field :search, placeholder: "何かお探しですか？", class: 'search-box input-default'
        = form.button type: 'submit', class: 'search-btn' do
          %i.fa.fa-search
    .pc-header__box__navi
      %navi.pc-header__box__navi--product
        %ul.navi-icon
          %li
            %h2
              = link_to '#', class: "pc-header__box__navi--product--root list-parent" do
                %i.fa.fa-list-ul
                %span カテゴリーから探す
            %ul.pc-header-nav-parent-wrap
              = render 'shared/category-parents', parents: @parents
          %li
            %h2
              = link_to '#', class: "pc-header__box__navi--product--root list-parent" do
                %i.fa.fa-tag
                %span ブランドから探す
      .pc-header__box__navi--user
        - if user_signed_in?
          %ul.pc-header__box__navi--user--list
            %li
              = link_to '#', class: "pc-header__box__navi--user--list--link" do
                %i.far.fa-bell.fa-lg
                %span お知らせ
            %li
              = link_to '#', class: "pc-header__box__navi--user--list--link" do
                %i.fa.fa-check.fa-lg
                %span やることリスト
            %li
              = link_to users_path, class: "pc-header__box__navi--user--list--link" do
                %i.fa.fa-circle.fa-lg
                %span マイページ
        - else
          %ul.pc-header__box__navi--user--login
            %li
              = link_to "ログイン", new_user_session_path, class: "sp-header-btn btn-red"
            %li
              = link_to "新規会員登録", new_user_path, class: "sp-header-btn header-signup"

%header.sp-header.visible-sp
  .sp-header__box
    %h1.logo
      = link_to root_path do
        = image_tag "mercari_logo_color.svg", alt: 'mercari'
    .sp-header__box__navi--user
      = link_to '#', class: "sp-header__box__navi--user--link" do
        %figure
          %i.far.fa-bell.fa-lg
      = link_to '#', class: "sp-header__box__navi--user--link" do
        %figure
          %i.fa.fa-check.fa-lg
      = link_to users_path, class: "sp-header__box__navi--user--link" do
        %figure
          %i.fa.fa-circle.fa-lg
  .sp-header__search-bar
    = form_with url: '#', class: "sp-header__search-bar__form" do |form|
      = form.text_field :search, placeholder: "何をお探しですか？", class: 'sp-search-box input-default'
      = form.button type: 'submit', class: 'search-btn' do
        %i.fa.fa-search
  .sp-header__navi
    = link_to '#', class: "sp-header__navi--category" do
      %i.fa.fa-list-ul
      %span カテゴリーから探す
    = link_to '#', class: "sp-header__navi--brand" do
      %i.fa.fa-tag
      %span ブランドから探す

app/views/shared/_item-content.html.haml
.main-box__items__row--item-box
  =link_to item_path(item.id), method: :get do
    = image_tag((item.images[0].file.first.url), width: '213', height: '213') if item.images.present?
    .main-box__items__row--item-box--body
      %h4
      = item.name
      .main-box__items__row--item-box--body--price
        ¥
        = item.price
        %p (税込)

app/views/shared/_item-detail-breadcrumbs.html.haml
%nav.common-breadcrumbs
  - breadcrumb :item, @item
  = breadcrumbs separator: " &#8811; "

app/views/shared/_item.html.haml
%section.main-box__items
  %h3
    =link_to "レディース 新着アイテム", "#"

  .main-box__items__row
    = render partial: 'shared/item-content', collection: items, as: 'item'

app/views/shared/_logout-breadcrumbs.html.haml
%nav.common-breadcrumbs
  - breadcrumb :logout_user, @user
  = breadcrumbs separator: " &#8811; "
  

app/views/shared/_mypage-breadcrumbs.html.haml
%nav.common-breadcrumbs
  - breadcrumb :users
  = breadcrumbs separator: " &#8811; "
  

app/views/shared/_register-breadcrumbs.html.haml
%nav.common-breadcrumbs
  - breadcrumb :register_user, @user
  = breadcrumbs separator: " &#8811; "
  

app/views/shared/_sell-btn.html.haml
= link_to :new_item, class: "fixed-circle-btn"  do
  %p.white_color 出品
  %i.fa.fa-camera

app/views/shared/_sign-up-footer.html.haml
.single-footer
  .nav
    %ul.clearfix
      %li
        = link_to 'プライバシーポリシー','#'
      %li
        = link_to 'メルカリ利用規約','#'
      %li
        = link_to '特定商取引に関する表記','#'

  .single-footer-logo
    = link_to image_tag('fooer-logo-gray.svg'), '#', class: 'footer-gray-logo'
  %p
    %small
      © 2019 Mercari