config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        #,
        #omniauth_callbacks: 'users/omniauth_callbacks',
        sessions: 'users/sessions'
      }
  root 'items#index'
  resources :items do
    member do
      get :confirm
      post :purchase
    end
  end

  as :user do

    get "/sign_up/registration" => "users/registrations#registration"#会員情報入力
    post "/sign_up/tel" => 'users/registrations#tel'#電話番号登録
    post "/sign_up/address" => 'users/registrations#address'#住所確認
    post "/sign_up/credit" => 'users/registrations#credit'#クレジットカード
    post "/sign_up/create" => 'users/registrations#create'#DBに保存
    get "/sign_up/done" => 'users/registrations#done'#完了ページ
    get "/users/:id/profile" => 'users#profile', as: :user_profile
    patch "/users/:id/profile" => 'users#profile_update' , as: :update_user_profile
    get "/users/:id/logout" => "users#logout", as: :user_logout
  end

  resources :cards, only: [:index, :new, :destroy, :create]

  #get "users/sign_up/registration", to: "users#new"
  resources :phonenumber
  resources :address
  resources :creditcards
  resources :users, only: [:index, :edit, :new] do
    member do
      get :logout
      get :register
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one :delivery, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  validates :name, presence: true
  validates :condition,presence: true
  validates :price, presence: true

  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :delivery, allow_destroy: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :confirm, :purchase]
  before_action :set_card, only: [:confirm, :purchase]
  before_action :set_parents, only: [:index, :show]

  def index
    @items = Item.includes(:images).sample(4)
  end

  def show
    @delivery = @item.delivery
  end

  def new
    @item = Item.new
    @item.images.build
    @item.build_delivery
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      respond_to do |format|
        format.json
        format.html { redirect_to root_path }
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    @item.update(item_params)
  end

  def destroy
    item = Item.find((params[:id]))
    if item.user_id == current_user.id
      item.destroy
    end
    redirect_to root_path
  end

  def confirm
    @card = Card.where(user_id: current_user.id).first
    if @card.blank?
      move_to_create_card
    else
      Payjp.api_key = "sk_test_611af3ae101ec243e28ddd29"
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = customer.cards.retrieve(@card.card_id)
      @card_brand = @card_information.brand

      case @card_brand
      when "Visa"
        @card_src = "visa.svg"
      when "JCB"
        @card_src = "jcb.svg"
      when "MasterCard"
        @card_src = "master-card.svg"
      when "American Express"
        @card_src = "american_express.svg"
      when "Diners Club"
        @card_src = "dinersclub.svg"
      when "Discover"
        @card_src = "discover.svg"
      end

    end
  end

  require 'payjp'

  def purchase
    Payjp::Charge.create(
      amount: @item.price,
      customer: @card.customer_id,
      currency: 'jpy'
    )
  end


  private

  def item_params
    params.require(:item).permit(:id, :name, :description, :brand, :size, :condition, :price, :category_id, images_attributes:[:id, :item_id, {file: []}], delivery_attributes:[:id, :payer, :method, :area, :date]).merge(user_id: current_user.id)
  end

  def image_params
    params.require(:image).permit(:id, :item_id, {file: []})
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end

  def set_parents
    @parents = Category.limit(14)
  end

  def move_to_create_card
    redirect_to new_card_path(user_id: current_user.id)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form-footer.html.haml
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        = link_to 'プライバシーポリシー', 'https://www.mercari.com/jp/privacy/'
      %li
        = link_to 'メルカリ利用規約', 'https://www.mercari.com/jp/tos/'
      %li
        = link_to '特定商取引に関する表記', 'https://www.mercari.com/jp/tokutei/'
  = link_to "#", class: "single-footer-logo" do
    = image_tag 'fooer-logo-gray.svg', alt: 'mercari', height: '65', width: '80'
  %p
    %small © 2019 Mercari
    

app/views/items/_show.html.haml
.wrapper
  =render "shared/header"

  .items-box-container
    .item-name
      %h1ニコちゃんロングTシャツ

    .item-main-content
      .item-main-content__images
        .image-main
          = image_tag('item_sample.jpg', width: '300', height: '300')
        .image-low
          .image-small
            = image_tag('item_sample.jpg', width: '75', height: '75')
          .image-small
            = image_tag('item_sample.jpg', width: '75', height: '75')
          .image-small
            = image_tag('item_sample.jpg', width: '75', height: '75')
          .image-small
            = image_tag('item_sample.jpg', width: '75', height: '75')
        .triangle

      %table.item-main-content__detail-table
        %tr
          %th 出品者
          %td
            =link_to '#' do
              %p あざお
            .rating
              .rating-good
                %i.fas.fa-grin
                100
              .rating-normal
                %i.fas.fa-meh
                0
              .rating-bad
                %i.fas.fa-frown
                0
        %tr
          %th カテゴリー
          %td
            =link_to '#' do
              %span ベビー・キッズ
              %br
              %i.fas.fa-chevron-right
              %span キッズ服
              %br
              %i.fas.fa-chevron-right
              %span トップス（その他）
        %tr
          %th ブランド
          %td
            =link_to '#' do
              %p シャネル
        %tr
          %th 商品の状態
          %td 非常に良い
        %tr
          %th 配送料の負担
          %td 送料込み(出品者負担)
        %tr
          %th 配送の方法
          %td らくらくメルカリ便
        %tr
          %th 配送元地域
          %td
            =link_to '#' do
              %p 奈良県
        %tr
          %th 発送日の目安
          %td 1~2日で発送


    .item-detail-price
      %span.item-detail-price--inclued-tax
        ¥100
      %span.item-detail-price--tax
        (税込)
      %span.item-detail-price--postage
        送料込み

    .item-buy__btn
      = link_to '#', class: 'buy-btn' do
        %p 売り切れました

    .item-detail-description
      %p
        ■商品ご覧頂き、誠にありがとうございます。
        %br
        ※今だけ、フォロワーになって下さった方に、300円のお値引きサービス中！！
        %br
        %br
        私の商品検索は、
        Boon・バッグ　
        検索してください。
        %br
        %br
        質問がありましたらコメントでよろしくお願いします！
        ■ 商品説明 ■
        まずはプロフを確認してください☆
        %br
        %br
        ■ 商品詳細 ■
        シンプルな落ち着いたお色味でどんな場面にも合い、
        どんな服にも合わせやすいお鞄です。使用感有！角擦れはございませんが
        多少の汚れはあります。内側はとても綺麗です☆
        使わなくなったのでどなたか使っていただける方お願いします。
        製造番号　H2K-9294
        %br
        %br
        【ブランド】
        シャネル
        %br
        %br
        【商品名】
        シャネル ロングTシャツ
        %br
        %br
        【仕様】
        ロングTシャツ
        %br
        %br
        【サイズ】
        %br
        縦：32
        %br
        横：31
        %br
        幅：7
        %br
        紐：130 多少調節可能
        %br
        %br
        ＊他にも数多くの商品を出品しているので、ぜひご覧ください。
        %br
        ＊複数購入、お取り置き(５日まで)もできるので、お気軽にお声がけくださいませ。
        %br
        ＊中古品になりますので、予めご理解いただきますよう、お願い致します^_^
        %br
        ※自宅保管、素人検品、素人寸法の誤差などにご理解がない方、神経質な方、完璧な物が欲しい方は購入お控えください。
        %br
        、お願い致します^_^
        %br
        ※自宅保管、素人検品、素人寸法の誤差などにご理解がない方、神経質な方、完璧な物が欲しい方は購入お控えください。
        %br

    .item-button-container
      .item-button-container-left
        .item-button-container__like
          %i.far.fa-heart
          %span いいね! 100
        .item-button-container__report
          = link_to '#', class: 'report-btn' do
            %i.far.fa-flag
            %span 不適切な商品の報告

      .item-button-container-right
        = link_to '#', class: 'report-btn' do
          %i.fas.fa-lock
          %span あんしん・あんぜんへの取り組み

  .items-detail-message__container
    .items-detail-message__body.clearfix
      .items-message-content
      = image_tag('user-icon.svg', class: 'user-face', width: '40', height: '40')
      .chatting
        .says
          %p こんにちわ
          .time
            %i.far.fa-clock
            %span 1日前

    .items-detail-message__body.clearfix
      .items-message-content
      = image_tag('user-icon.svg', class: 'user-face', width: '40', height: '40')
      .chatting
        .says
          %p こんにちわ
          .time
            %i.far.fa-clock
            %span 1日前

    .items-detail-message__body.clearfix
      .items-message-content
      = image_tag('user-icon.svg', class: 'user-face', width: '40', height: '40')
      .chatting
        .says
          %p こんにちわ
          .time
            %i.far.fa-clock
            %span 1日前

    .items-detail-message__body.clearfix
      .items-message-content
      = image_tag('user-icon.svg', class: 'user-face', width: '40', height: '40')
      .chatting
        .says
          %p こんにちわ
          .time
            %i.far.fa-clock
            %span 1日前


    .items-message-content
      %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      = form_with do |f|
        = f.text_area :comment, type: 'input', class: 'message-content'
      .items-message-content__btn
        = link_to '#', class: 'messege-btn' do
          %span 売り切れのためコメントできません。

  %ul.nav-item-link
    %li.nav-item-link__prev
      =link_to '#' do
        %i.fas.fa-chevron-left
        %span ディズニーヴィランズ 2個セット バッジ バッチ
    %li.nav-item-link__next
      =link_to '#' do
        %span 楽天パンダ ノート&マスキングテープセット
        %i.fas.fa-chevron-right

  .item-social-mediabox
    %ul.social-mediabox
      .facebook-square
        %li
          = link_to '#', class: 'facebook-icon' do
            %i.fab.fa-facebook-square
      .twitter-square
        %li
          = link_to '#', class: 'twitter-icon' do
            %i.fab.fa-twitter-square
      %li.pinterest-square
        = link_to '#', class: 'pinterest-icon' do
          %i.fab.fa-pinterest-square




  .items-user-box
    %section.items-user-box__items
      %h4
        =link_to "あざおさんのその他の出品", "#"

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'item_sample.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ニコちゃんロングTシャツ 100
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'item_sample.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ニコちゃんロングTシャツ 100
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'item_sample.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ニコちゃんロングTシャツ 100
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

  .items-user-box
    %section.items-user-box__items
      %h4
        =link_to "シャネルのTシャツのその他の出品", "#"

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'item_sample.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ニコちゃんロングTシャツ 100
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'item_sample.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ニコちゃんロングTシャツ 100
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'item_sample.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ニコちゃんロングTシャツ 100
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

  =render "shared/sell-btn"

  =render "shared/app-banner"

  =render "shared/footer"
  

app/views/items/_upload.html.haml
.items-container__upload
  .items-container__upload__items.have-item-1
    %ul
      %li.upload-item
        %figure.upload-figure.square
          = image_tag 'list_item_example1.jpg'
        .upload-btn
          = link_to('編集', '#', {class: 'upload-btn__edit'})
          = link_to('削除', '#', {class: 'upload-btn__delete'})
.items-container__drop-box
  %input.items-container__drop-file{type: "file", name: "image1", style: "display: none;", multiple: true}
  %pre.visible-pc
    ドラッグ & ドロップ
    またはクリックしてアップロード
  %i.icon-camera

%ul
  %li.upload-item
    %figure.upload-figure.square
      = image_tag 'list_item_example1.jpg'
    .upload-btn
      = link_to('編集', '#', {class: 'upload-btn__edit'})
      = link_to('削除', '#', {class: 'upload-btn__delete'})

app/views/items/confirm.html.haml
.single-container
  %header.single-header
    %h1
      = link_to('https://www.mercari.com/jp/') do
        = image_tag 'mercari_logo_color.svg', alt: 'mercari', height: '49px', width: '185px'
  %main.single-main
    %section.buy-item-container
      %h2.single-head
        購入を確定しますか？
      %section.buy-content.buy-item
        .buy-content__inner
          %h3.buy-item__image
            = image_tag "#{@item.images[0].file.first.url}"
          %p.buy-item__name.bold
            = @item.name
          = form_with url: purchase_item_path, class: "buy-form" do |f|
            %p.buy-item__price--ja.bold
              = "¥#{@item.price}"
              %span.item-shipping-fee.f14.bold 送料込み
            %ul.buy-item__accordion.not-have
              %li.buy-item__accordion--parent
                .buy-item__accordion--child
                  ポイントはありません
            %ul.buy-item__payment
              %li.buy-item__payment--list.buy-you-pay.bold
                .buy-price 支払金額
                .buy-price
                  %span{data: {buy: {pay: "#{@item.price}"}}}
                    = "¥#{@item.price}"
              = f.submit "購入する", {class: "btn-box__default  btn--purchase btn-box--red"}
              .modal-overlay
              .modal-screen
                %p 購入が完了しました。
                %a.close-btn TOPへ戻る


      %section.buy-content.buy-user__info
        .buy-content__inner
          %h3 配送先
          %address.buy-user__info--text
            〒165-0033(postal_code)
            %br
            東京都(prefecture) 中野区(city)
            ◯◯5-1-11(street_address)
            △△◯アパート(building)
            %br
            愛川(family_name_kanji) 令菜(first_name_kanji)
          %p.buy-user__info--text
          = link_to "#", {class: 'buy-user__info--text--fix'} do
            %span 変更する
            %i.fas.fa-chevron-right
      %section.buy-content.buy-user__info{data: {buy: 'pay-method'}}
        .buy-content__inner
          %h3 支払方法
          %p.buy-user__info--text
            = "**** **** **** " + @card_information.last4
            %br
            - exp_month = @card_information.exp_month.to_s
            - exp_year = @card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          %figure
            = image_tag "credit-cards/#{@card_src}", alt: @card_brand, height: '20', width: '26'
          %p
          = link_to new_card_path, {class: 'buy-user__info--text--fix'} do
            %span 変更する
            %i.fas.fa-chevron-right
  = render 'form-footer'

app/views/items/index.html.haml
.wrapper
  =render "shared/header"
  %main.white
    .swiper-container.top-carousel
      .swiper-wrapper
        .swiper-slide
          = image_tag 'carousel/banner-bokurano-heisei.jpg', alt: 'swipe01'
        .swiper-slide
          = image_tag 'carousel/banner-natsukashi.jpg', alt: 'swipe02'
        .swiper-slide
          = image_tag 'carousel/banner-new-life.jpg', alt: 'swipe03'
      .swiper-button-prev.swiper-button-custome
        %i.fas.fa-angle-double-left
      .swiper-button-next.swiper-button-custome
        %i.fas.fa-angle-double-right
      .swiper-pagination
    .main-box
      %h2 ピックアップカテゴリー
      %section.main-box__items
        %h3
          =link_to "レディース 新着アイテム", "#"

        .main-box__items__row
          = render partial: 'shared/item-content', collection: @items, as: 'item'

    =render "shared/sell-btn"

    =render "shared/app-banner"

    =render "shared/footer"

= javascript_include_tag "swiper", "carousel"

app/views/items/show.html.haml
.wrapper
  =render "shared/header"
  =render 'shared/item-detail-breadcrumbs'

  .items-box-container
    .item-name
      %h1= @item.name

    .item-main-content
      .item-main-content__images
        .image-main
          = image_tag("#{@item.images[0].file[0].url}", width: '300', height: '300')
        .image-low
          .image-small
            - @item.images[0].file.each do |file|
              = image_tag("#{file.url}", width: '75', height: '75', class:'small-image')

      %table.item-main-content__detail-table
        %tr
          %th 出品者
          %td
            =link_to "#" do
              %p あざおさん
            .rating
              .rating-good
                %i.fas.fa-grin
                100
              .rating-normal
                %i.fas.fa-meh
                0
              .rating-bad
                %i.fas.fa-frown
                0
        %tr
          %th カテゴリー
          %td
            =link_to '#' do
              %span ベビー・キッズ
              %br
              %i.fas.fa-chevron-right
              %span キッズ服
              %br
              %i.fas.fa-chevron-right
              %span トップス（その他）
        / - if @item.brand.present?
        /   %tr
        /     %th ブランド
        /     %td
        /       =link_to '#' do
        /         %p=@item.brand
        / - if @item.size.present?
        /   %tr
        /     %th サイズ
        /     %td=@item.size
        %tr
          %th 商品の状態
          %td=@item.condition
        %tr
          %th 配送料の負担
          %td=@delivery.payer
        %tr
          %th 配送の方法
          %td=@delivery.method
        %tr
          %th 配送元地域
          %td
            =link_to '#' do
              %p=@delivery.area
        %tr
          %th 発送日の目安
          %td=@delivery.date


    .item-detail-price
      %span.item-detail-price--inclued-tax
        ¥
        = @item.price
      %span.item-detail-price--tax
        (税込)
      %span.item-detail-price--postage
        送料込み

    - if ((!user_signed_in?) || (current_user.id != @item.user_id))
      .item-buy__btn
        = link_to confirm_item_path(params[:id]), class: 'buy-btn' do
          %p 購入画面に進む
    - else
      .item-edit__btn
        = link_to edit_item_path(@item.id) do
          %p 商品の編集
      %p.text-center or
      .item-delete__btn
        = link_to item_path(@item.id), method: :delete do
          %p この商品を削除する

    .item-detail-description
      %p= @item.description

    .item-button-container
      .item-button-container-left
        .item-button-container__like
          %i.far.fa-heart
          %span いいね! 100
        .item-button-container__report
          = link_to '#', class: 'report-btn' do
            %i.far.fa-flag
            %span 不適切な商品の報告

      .item-button-container-right
        = link_to '#', class: 'report-btn' do
          %i.fas.fa-lock
          %span あんしん・あんぜんへの取り組み

  .items-detail-message__container
    .items-detail-message__body.clearfix
      .items-message-content
      = image_tag('user-icon.svg', class: 'user-face', width: '40', height: '40')
      .chatting
        .says
          %p こんにちわ
          .time
            %i.far.fa-clock
            %span 1日前

    .items-detail-message__body.clearfix
      .items-message-content
      = image_tag('user-icon.svg', class: 'user-face', width: '40', height: '40')
      .chatting
        .says
          %p こんにちわ
          .time
            %i.far.fa-clock
            %span 1日前

    .items-message-content
      %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      = form_with do |f|
        = f.text_area :comment, type: 'input', class: 'message-content'
      .items-message-content__btn
        = link_to '#', class: 'messege-btn' do
          %span コメントする

  %ul.nav-item-link
    %li.nav-item-link__prev
      =link_to '#' do
        %i.fas.fa-chevron-left
        %span ディズニーヴィランズ 2個セット バッジ バッチ
    %li.nav-item-link__next
      =link_to '#' do
        %span 楽天パンダ ノート&マスキングテープセット
        %i.fas.fa-chevron-right

  .item-social-mediabox
    %ul.social-mediabox
      .facebook-square-box
        %li
          = link_to '#', class: 'facebook-icon' do
            %i.fab.fa-facebook-square
      .twitter-square-box
        %li
          = link_to '#', class: 'twitter-icon' do
            %i.fab.fa-twitter-square
      %li.pinterest-square-box
        = link_to '#', class: 'pinterest-icon' do
          %i.fab.fa-pinterest-square




  .items-user-box
    %section.items-user-box__items
      %h4
        =link_to "あざお"+"さんのその他の出品", "#"

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'item_sample.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ニコちゃんロングTシャツ 100
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'item_sample.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ニコちゃんロングTシャツ 100
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'list_item_example1.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ピカチュウ
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

  .items-user-box
    %section.items-user-box__items
      %h4
        =link_to "シャネル"+"のTシャツのその他の出品", "#"

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'item_sample.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ニコちゃんロングTシャツ 100
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'item_sample.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ニコちゃんロングTシャツ 100
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

      .items-user-box__items__row
        .items-user-box__items__row__userselling-item-box
          =link_to '#' do
            = image_tag 'list_item_example1.jpg', width: 220, height: 220
            .items-user-box__items__row__userselling-item-box--body
              %h5 ピカチュウ 100
              .items-user-box__items__row__userselling-item-box--body--price
                ¥ 100
                %p (税込)

  =render "shared/sell-btn"

  =render "shared/app-banner"

  =render "shared/footer"