config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        #,
        #omniauth_callbacks: 'users/omniauth_callbacks',
        sessions: 'users/sessions'
      }
  root 'items#index'
  resources :items do
    member do
      get :confirm
      post :purchase
    end
  end

  as :user do

    get "/sign_up/registration" => "users/registrations#registration"#会員情報入力
    post "/sign_up/tel" => 'users/registrations#tel'#電話番号登録
    post "/sign_up/address" => 'users/registrations#address'#住所確認
    post "/sign_up/credit" => 'users/registrations#credit'#クレジットカード
    post "/sign_up/create" => 'users/registrations#create'#DBに保存
    get "/sign_up/done" => 'users/registrations#done'#完了ページ
    get "/users/:id/profile" => 'users#profile', as: :user_profile
    patch "/users/:id/profile" => 'users#profile_update' , as: :update_user_profile
    get "/users/:id/logout" => "users#logout", as: :user_logout
  end

  resources :cards, only: [:index, :new, :destroy, :create]

  #get "users/sign_up/registration", to: "users#new"
  resources :phonenumber
  resources :address
  resources :creditcards
  resources :users, only: [:index, :edit, :new] do
    member do
      get :logout
      get :register
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card
  before_action :set_parents, only: [:index, :new]


  def index #CardのデータをPayjpに送って情報を取り出す
    if @card.present?
      Payjp.api_key = "sk_test_611af3ae101ec243e28ddd29"
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = customer.cards.retrieve(@card.card_id)
      @card_brand = @card_information.brand

      case @card_brand
      when "Visa"
        @card_src = "visa.svg"
      when "JCB"
        @card_src = "jcb.svg"
      when "MasterCard"
        @card_src = "master-card.svg"
      when "American Express"
        @card_src = "american_express.svg"
      when "Diners Club"
        @card_src = "dinersclub.svg"
      when "Discover"
        @card_src = "discover.svg"
      end
      
    end
  end

  def new
    card = Card.where(user_id: current_user.id).first
    redirect_to action: "index" if card.present?
  end

  def create #PayjpとCardのデータベースを作成
    Payjp.api_key = 'sk_test_611af3ae101ec243e28ddd29'
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        description: 'test',
        email: current_user.email,
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "index"
      else
        redirect_to action: "create"
      end
    end
  end

  def destroy #PayjpとCardのデータベースを削除
    Payjp.api_key = "sk_test_611af3ae101ec243e28ddd29"
    customer = Payjp::Customer.retrieve(@card.customer_id)
    customer.delete
    if @card.destroy
      redirect_to action: "index", notice: "削除しました"
    else
      redirect_to action: "index", alert: "削除できませんでした"
    end
  end

  private

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end

  def set_parents
    @parents = Category.limit(14)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_add-card.html.haml
.content__credit-cards__add
  .content__credit-cards__add--btn
    = link_to new_card_path, class: 'btn' do
      %p.white_color
        %i.far.fa-credit-card
        クレジットカードを追加する

app/views/cards/index.html.haml
.wrapper

  = render 'shared/header'
  = render 'shared/card-method-breadcrumbs'

  .container.clearfix

    = render 'users/leftbar'

    .main
      .content
        .content__title
          %h2 支払い方法
        .content__credit-cards
          %h3 クレジットカード一覧
          - if @card.present?
            %ul.content__credit-cards__list
              %li
                = form_with url: card_path(@card.id), method: :delete, local: true, id: 'charge-form' do |f|
                  %figure
                    - @card_brand
                    = image_tag "credit-cards/#{@card_src}", width: '26', height: '20', alt: @card_brand, id: "card_image"
                  .content__credit-cards__list--pay-num
                    = "**** **** **** " + @card_information.last4
                  .content__credit-cards__list--pay-num
                    - exp_month = @card_information.exp_month.to_s
                    - exp_year = @card_information.exp_year.to_s.slice(2,3)
                    = exp_month + " / " + exp_year
                  %input{type: "hidden", name: "card_id", value: ""}
                  = f.submit "削除する", {class: "content__credit-cards__list__remove"}
                  - if flash[:notice]
                    .alert.alert-success
                    = flash[:notice]
                  - if flash[:alert]
                    .alert.alert-dange
                    = flash[:alert]
          - else
            = render 'add-card'
          = link_to '#', class: 'explain-payment' do
            %span 支払い方法について
            %i.fas.fa-angle-right

  = render 'shared/sell-btn'
  = render "shared/app-banner"
  = render 'shared/footer'

app/views/cards/new.html.haml
.wrapper#addCard

  = render 'shared/header'
  = render 'shared/card-new-breadcrumbs'

  .container.clearfix

    = render 'users/leftbar'

    .main
      .content
        .content__title
          %h2 クレジットカード情報入力
        .content__credit-card
          .content__credit-card__inner
            = form_with url: cards_path, method: :post, html: { name: "inputForm" } do |f|
              = f.label :カード番号, class: 'label'
              %span 必須
              = f.text_field :card_number, type: 'text', class: 'input-number', placeholder: '半角数字のみ', maxlength: "16"
              .cards-images
                = image_tag "credit-cards/visa.svg"
                = image_tag "credit-cards/master-card.svg"
                = image_tag "credit-cards/saison-card.svg"
                = image_tag "credit-cards/jcb.svg"
                = image_tag "credit-cards/american_express.svg"
                = image_tag "credit-cards/dinersclub.svg"
                = image_tag "credit-cards/discover.svg"
              .cards-expire
                = f.label :有効期限, class: 'label'
                %span 必須
                %br
                .cards-expire__wrap
                  = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'input-expire'
                  %i.fas.fa-chevron-down.fa-lg
                  %span.expire-text 月
                  %br
                .cards-expire__wrap
                  = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'input-expire'
                  %i.fas.fa-chevron-down.fa-lg
                  %span.expire-text 年
              .cards-expire
                = f.label :セキュリティコード, class: 'label'
                %span 必須
                = f.text_field :cvc, type: 'text', class: 'input-number', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4"
              .credit-card--note
                %i.fas.fa-question-circle
                カード裏面の番号とは？
              .content-bottom#card_token
                = f.submit '追加する', class: 'content-bottom--add-btn', id: 'token_submit'

  = render 'shared/sell-btn'
  = render "shared/app-banner"
  = render 'shared/footer'

:javascript
  document.addEventListener(
  "DOMContentLoaded", (e) => {
    Payjp.setPublicKey("pk_test_5c749df69c612790371ab4d1");
    const btn = document.getElementById('token_submit'); //IDがtoken_submitの場合に取得される
    btn.addEventListener("click", (e) => {　//ボタンが押されたときに作動します
      e.preventDefault();　//ボタンを一旦無効化します

      //カード情報生成
      const card = {
        number: document.getElementById("card_number").value,
        cvc: document.getElementById("cvc").value,
        exp_month: document.getElementById("exp_month").value,
        exp_year: document.getElementById("exp_year").value
      }; //入力されたデータを取得します。

      //トークン生成
      Payjp.createToken(card, (status, response) => {
        if (status === 200) { //成功した場合
          $("#card_number").removeAttr("name");
          $("#cvc").removeAttr("name");
          $("#exp_month").removeAttr("name");
          $("#exp_year").removeAttr("name"); //データを自サーバにpostしないように削除
          $("#card_token").append(
            $('<input type="hidden" name="payjp-token">').val(response.id)
          ); //取得したトークンを送信できる状態にします
          document.inputForm.submit();
          alert("登録が完了しました"); //確認用
        } else {
          alert("カード情報が正しくありません。"); //確認用
        }
      });
    });
  },false);